module.exports = {
	printWidth: 100,
	tabWidth: 2,
	useTabs: true,
	semi: false,
	singleQuote: true,
	quoteProps: "as-needed",
	jsxSingleQuote: false,
	trailingComma: "all",
	bracketSpacing: true,
	jsxBracketSameLine: false,
	arrowParens: "avoid",
	rangeEnd: Infinity,
	parser: "",
	filepath: "",
	requirePragma: false,
	insertPragma: false,
	proseWrap: "preserve",
	htmlWhitespaceSensitivity: "css",
	vueIndentScriptAndStyle: true,
	endOfLine: "lf",
};
